-- USE THE DATABASE
USE CSD_DATABASE;

-- INSERT DATA INTO CSD_SOURCES
INSERT INTO CSD_SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATALOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('AMAZON', 'JSON', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('UBER', 'XML', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('AT&T', 'CSV', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- INSERT DATA INTO CSD_SUPPORT_AREAS
-- AMAZON
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('ORDER ISSUES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PRODUCT INQUIRIES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SHIPPING & DELIVERY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ACCOUNT & SECURITY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('RETURNS & REFUNDS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PRIME MEMBERSHIP', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('MARKETPLACE & THIRD-PARTY SELLERS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT AREA FROM AMAZON', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- UBER
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('RIDE ISSUES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('DRIVER/PASSENGER CONCERNS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SAFETY & SECURITY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ACCOUNT & PROFILE MANAGEMENT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PROMOTIONS & DISCOUNT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('DRIVER SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('UBER EATS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ACCESIBILITY SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT AREA FROM UBER', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- AT&T
INSERT INTO CSD_SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('ACCOUNT MANAGEMENT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SUPPORT OUTAGES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('NEW CUSTOMER ONBOARDING', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('MOBILE & WIRELESS SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('HOME SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SECURITY & PRIVACY', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BUSINESS SERVICES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('LOYALTY & RETENTIONS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT AREA FROM AT&T', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- INSERT DATA INTO CSD_AGENTS
-- AMAZON
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('JOHN', 'A.', 'DOE', 'JDOE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('JANE', 'B.', 'SMITH', 'JSMITH', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ALICE', 'C.', 'JOHNSON', 'AJOHNSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BOB', 'D.', 'WILLIAMS', 'BWILLIAMS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('CHARLIE', 'E.', 'BROWN', 'CBROWN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('DAVID', 'F.', 'JONES', 'DJONES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('EVE', 'G.', 'GARCIA', 'EGARCIA', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('FRANK', 'H.', 'MARTINEZ', 'FMARTINEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('GRACE', 'I.', 'HERNANDEZ', 'GHERNANDEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('HANK', 'J.', 'LOPEZ', 'HLOPEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 1, CURRENT_TIMESTAMP, '2999-12-31');

-- UBER
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('IVY', 'K.', 'GONZALEZ', 'IGONZALEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('JACK', 'L.', 'WILSON', 'JWILSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('KARA', 'M.', 'ANDERSON', 'KANDERSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('LEO', 'N.', 'THOMAS', 'LTHOMAS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('MIA', 'O.', 'TAYLOR', 'MTAYLOR', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('NATE', 'P.', 'MOORE', 'NMOORE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('OLIVIA', 'Q.', 'JACKSON', 'OJACKSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PAUL', 'R.', 'WHITE', 'PWHITE', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('QUINN', 'S.', 'HARRIS', 'QHARRIS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('RYAN', 'T.', 'MARTIN', 'RMARTIN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 1, CURRENT_TIMESTAMP, '2999-12-31');

-- AT&T
INSERT INTO CSD_AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('SARA', 'U.', 'THOMPSON', 'STHOMPSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TOM', 'V.', 'GARCIA', 'TGARCIA', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('UMA', 'W.', 'MARTINEZ', 'UMARTINEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('VICTOR', 'X.', 'HERNANDEZ', 'VHERNANDEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('WENDY', 'Y.', 'LOPEZ', 'WLOPEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('XANDER', 'Z.', 'GONZALEZ', 'XGONZALEZ', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('YARA', 'A.', 'WILSON', 'YWILSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ZANE', 'B.', 'ANDERSON', 'ZANDERSON', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ABBY', 'C.', 'THOMAS', 'ATHOMAS', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('EDGAR', 'D.', 'JONES', 'EJONES', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 1, CURRENT_TIMESTAMP, '2999-12-31');

-- INSERT DATA INTO CSD_CUSTOMER_TYPES
-- AMAZON
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('FIRST-TIME SHOPPER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('FREQUENT BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PRIME MEMBER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('HIGH-SPENDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BUDGET SHOPPER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BUSINESS BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TECH-SAVVY BUYER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('GIFT GIVER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('RETURNS & REFUND SEEKER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('COMPLAINT-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CUSTOMER TYPE FROM AMAZON SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31');
	
-- UBER
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('FIRST-TIME RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('FREQUENT RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('COMMUTER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TRAVELER/TOURIST', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('UBER EATS CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('CORPORATE RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('DRIVER-PARTNER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('PROMO-SEEKER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SAFETY-CONSCIOUS RIDER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('ACCESSIBILITY-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER TYPE FROM UBER SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- AT&T
INSERT INTO CSD_CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('NEW CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('LONG-TERM CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('TECH-SAVVY USER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('SENIOR CITIZEN', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BUSINESS OWNER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('FAMILY PLAN MANAGER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('FREQUENT TRAVELER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('BUDGET-CONSCIOUS CUSTOMER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('HEAVY DATA USER', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31'),
    ('DEVICE ENTHUSIAST', (SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CUSTOMER TYPE FROM AT&T SOURCE', 1, CURRENT_TIMESTAMP, '2999-12-31');

-- INSERT DATA INTO CSD_TABLE_TYPES
INSERT INTO CSD_TABLE_TYPES (TABLE_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('DATA MART TABLE', 'TABLE THAT STORES ACTUAL DATA FOR WHICH THE DATABASE HAS BEEN CREATED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('DATA STANDARD TABLE', 'TABLE THAT DEFINES THE STANDARD VALUES FOR A COLUMN OF THE DATA MART TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('DATA AUDIT TABLE', 'TABLE THAT STORES AUDIT INFORMATION OF SPECIFIC ACTIONS ON DATA MART TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('DATABASE INFORMATION TABLE', 'TABLE THAT STORES THE DATABASE RELATED INFORMATION', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');

-- INSERT DATA INTO CSD_TABLE_LOAD_TYPES
INSERT INTO CSD_TABLE_LOAD_TYPES (TABLE_LOAD_TYPE_NAME, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('PYSPARK ETL', 'THE TABLE SHALL BE LOADED USING A PYSPARK ETL FLOW', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('MANUAL DML', 'THE TABLE SHALL BE LOADED USING A DML STATEMENT MANUALLY', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');

-- INSERT DATA INTO CSD_DATA_DICTIONARY
-- AMAZON
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RECORD_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (UNIQUE)', 'PRIMARY KEY OF THE SUPPORT DATA', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (CAN REPEAT)', 'UNIQUE IDENTIFIER FOR AN INTERACTION', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SUPPORT_CATEGORY', 'STRING', '"ORDER ISSUES", "PRODUCT INQUIRIES", "SHIPPING & DELIVERY", "ACCOUNT & SECURITY", "PAYMENTS & BILLING", "RETURNS & REFUNDS", "TECHNICAL SUPPORT", "PROMOTIONS & DISCOUNTS", "PRIME MEMBERSHIP", "MARKETPLACE & THIRD-PARTY SELLERS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ORDER ISSUES', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'AGENT_PSEUDO_NAME', 'STRING', '"JDOE", "JSMITH", "AJOHNSON", "BWILLIAMS", "CBROWN", "DJONES", "EGARCIA", "FMARTINEZ", "GHERNANDEZ", "HLOPEZ"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'JDOE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'CONTACT_DATE', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE OF THE INTERATION IN DD/MM/YYYY HH:MI:SS FORMAT', '01/01/2021 00:00:00', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_STATUS', 'STRING', '"COMPLETED", "DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'COMPLETED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'TYPE_OF_CUSTOMER', 'STRING', '"FIRST-TIME SHOPPER", "FREQUENT BUYER", "PRIME MEMBER", "HIGH-SPENDER", "BUDGET SHOPPER", "BUSINESS BUYER", "TECH-SAVVY BUYER", "GIFT GIVER", "RETURNS & REFUND SEEKER", "COMPLAINT-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'FIRST-TIME SHOPPER', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'INTERACTION_DURATION', 'INTEGER', 'POSITIVE INTEGERS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN SECONDS', '120', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'TOTAL_TIME', 'INTEGER', 'POSITIVE INTEGERS', 'TOTAL TIME TAKEN TO COMPLETE THE INTERACTION AND ANY WORK RELATED TO INTERACTION AFTER CALL IN SECONDS', '150', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'STATUS_OF_CUSTOMER_INCIDENT', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RESOLVED_IN_FIRST_CONTACT', 'STRING', '"YES", "NO"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', 'YES', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'SOLUTION_TYPE', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AMAZON'), 'RATING', 'INTEGER', '1 - 10', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '10', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');

-- UBER
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED VALUE', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CONTACT_REGARDING', 'STRING', '"RIDE ISSUES", "DRIVER/PASSENGER CONCERNS", "PAYMENTS & BILLING", "SAFETY & SECURITY", "ACCOUNT & PROFILE MANAGEMENT", "PROMOTIONS & DISCOUNT", "DRIVER SUPPORT", "TECHNICAL SUPPORT", "UBER EATS", "ACCESIBILITY SUPPORT"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'RIDE ISSUES', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'AGENT_CODE', 'STRING', '"IGONZALEZ", "JWILSON", "KANDERSON", "LTHOMAS", "MTAYLOR", "NMOORE", "OJACKSON", "PWHITE", "QHARRIS", "RMARTIN"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'IGONZALEZ', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'DATE_OF_INTERACTION', 'DATE', 'DATES AFTER 2021 JAN', 'DATE IN YYYYMMDD FORMAT', '20210401', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'STATUS_OF_INTERACTION', 'STRING', '"INTERACTION COMPLETED", "CUSTOMER DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'INTERACTION COMPLETED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TYPE_OF_INTERACTION', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CHAT', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CUSTOMER_TYPE', 'STRING', '"FIRST-TIME RIDER", "FREQUENT RIDER", "COMMUTER", "TRAVELER/TOURIST", "UBER EATS CUSTOMER", "CORPORATE RIDER", "DRIVER-PARTNER", "PROMO-SEEKER", "SAFETY-CONSCIOUS RIDER", "ACCESSIBILITY-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'PROMO-SEEKER', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'CONTACT_DURATION', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN TIMESTAMP FORMAT', '00:02:00', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'AFTER_CONTACT_WORK_TIME', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN TIMESTAMP FORMAT', '00:01:00', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'INCIDENT_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'FIRST_CONTACT_SOLVE', 'BOOLEAN', '"1", "FALSE"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TYPE_OF_RESOLUTION', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'SUPPORT_RATING', 'INTEGER', '1 - 5', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '5', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'UBER'), 'TIME_STAMP', 'TIMESTAMP', 'TIMESTAMP VALUES', 'TIMESTAMP OF THE RECORD CREATION', '01/01/2024 00:00:00', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');


-- AT & T
INSERT INTO CSD_DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TICKET_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED INTEGER VALUES', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'SUPPORT_CATEGORY', 'STRING', '"ACCOUNT MANAGEMENT", "TECHNICAL SUPPORT", "SUPPORT OUTAGES", "NEW CUSTOMER ONBOARDING", "MOBILE & WIRELESS SERVICES", "HOME SERVICES", "PROMOTIONS & DISCOUNTS", "SECURITY & PRIVACY", "BUSINESS SERVICES", "LOYALTY & RETENTIONS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ACCOUNT MANAGEMENT', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'AGENT_NAME', 'STRING', '"STHOMPSON", "TGARCIA", "UMARTINEZ", "VHERNANDEZ", "WLOPEZ", "XGONZALEZ", "YWILSON", "ZANDERSON", "ATHOMAS", "EDJONES"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'STHOMPSON', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'DATE_OF_CALL', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE IN MMDDYYYYHHMISS FORMAT', '01012024000000', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CALL_STATUS', 'STRING', '"CALL COMPLETED", "CALL DROPPED", "CALL TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'CALL COMPLETED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'CALL_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TYPE_OF_CUSTOMER', 'STRING', '"NEW CUSTOMER", "LONG-TERM CUSTOMER", "TECH-SAVVY USER", "SENIOR CITIZEN", "BUSINESS OWNER", "FAMILY PLAN MANAGER", "FREQUENT TRAVELER", "BUDGET-CONSCIOUS CUSTOMER", "HEAVY DATA USER", "DEVICE ENTHUSIAST"', 'INTERNAL CUSTOMER TYPE', 'NEW CUSTOMER', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'DURATION', 'INTEGER', 'POSTIVE INTEGER', 'DURATION OF THE INTERACTION WITH CUSTOMER IN TIMESTAMP FORMAT', '120', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'WORK_TIME', 'INTEGER', 'POSTIVE INTEGER', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN TIMESTAMP FORMAT', '30', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'TICKET_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RESOLVED_IN_FIRST_CONTACT', 'INTEGER', '1, 0', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', '1', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RESOLUTION_CATEGORY', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
	((SELECT SOURCE_ID FROM CSD_SOURCES WHERE SOURCE_NAME = 'AT&T'), 'RATING', 'STRING', '"WORST", "BAD", "NEUTRAL", "GOOD", "BEST"', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', 'BEST', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');

-- INSERT DATA INTO CSD_TABLE_NAMES
INSERT INTO CSD_TABLE_NAMES (TABLE_NAME, TABLE_TYPE_ID, DESCRIPTION, TABLE_LOAD_TYPE_ID, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES 
    ('CSD_SOURCES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SOURCES THAT ARE BEING USED IN THE DATA MART', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_SUPPORT_AREAS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SUPPORT AREAS FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_AGENTS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF AGENT NAMES FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_CUSTOMER_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF CUSTOMER TYPES FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_TABLE_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TYPES OF TABLES PRESENT IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_TABLE_LOAD_TYPES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON HOW A TABLE GETS LOADED WITH DATA', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_DATA_DICTIONARY', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE DATA RECEIVED FROM EACH SOURCE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_DATA_LOADS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA AUDIT TABLE'), 'TABLE TO STORE THE INFORMATION OF EACH PYSPARK LOAD EXECUTED', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'PYSPARK ETL'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_TABLE_NAMES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TABLES IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_TABLE_COLUMNS', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE COLUMNS OF THE TABLES IN THE DATABASE', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'MANUAL DML'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('CSD_DATA_MART', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA MART TABLE'), 'TABLE TO STORE THE ACTUAL DATA ON WHICH DASHBOARDS ARE TO BE CREATED', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'PYSPARK ETL'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    ('STREAMING_DATA_ARCHIVES', (SELECT TABLE_TYPE_ID FROM CSD_TABLE_TYPES WHERE TABLE_TYPE_NAME = 'DATA MART TABLE'), 'TABLE TO STORE THE XML STREAMING DATA', (SELECT TABLE_LOAD_TYPE_ID FROM CSD_TABLE_LOAD_TYPES WHERE TABLE_LOAD_TYPE_NAME = 'PYSPARK ETL'), 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');


-- INSERT STATEMENTS FOR CSD_TABLE_COLUMNS
INSERT INTO CSD_TABLE_COLUMNS (TABLE_ID, COLUMN_NAME, DATA_TYPE, FIELD_LENGTH, DESCRIPTION, ACTIVE_FLAG, START_DATE, END_DATE)
VALUES
    -- CSD_SOURCES (TABLE_ID = 1)
    (1, 'SOURCE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'SOURCE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'SOURCE_FILE_TYPE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'DATA_LOAD_STRATEGY', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'LAST_LOADED_RECORD_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (1, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_SUPPORT_AREAS (TABLE_ID = 2)
    (2, 'SUPPORT_AREA_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'SUPPORT_AREA_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'SOURCE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (2, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_AGENTS (TABLE_ID = 3)
    (3, 'AGENT_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'FIRST_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'MIDDLE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'LAST_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'PSEUDO_CODE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'SOURCE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (3, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_CUSTOMER_TYPES (TABLE_ID = 4)
    (4, 'CUSTOMER_TYPE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'CUSTOMER_TYPE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'SOURCE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (4, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_TABLE_TYPES (TABLE_ID = 5)
    (5, 'TABLE_TYPE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (5, 'TABLE_TYPE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (5, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (5, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (5, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (5, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_TABLE_LOAD_TYPES (TABLE_ID = 6)
    (6, 'TABLE_LOAD_TYPE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (6, 'TABLE_LOAD_TYPE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (6, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (6, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (6, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (6, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_DATA_DICTIONARY (TABLE_ID = 7)
    (7, 'DATA_DICTIONARY_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'SOURCE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'FIELD_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'DATA_TYPE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'VALUES_ALLOWED', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'EXAMPLE', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (7, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_DATA_LOADS (TABLE_ID = 8)
    (8, 'DATA_LOAD_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'DAG_ID', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'LOAD_STATUS', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'LOAD_START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'LOAD_END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'TOTAL_UPSERT_COUNT', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'VALID_COUNT', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'INVALID_COUNT', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'DATA_VALID_PERCENTAGE', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (8, 'LOAD_DURATION', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_TABLE_NAMES (TABLE_ID = 9)
    (9, 'TABLE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'TABLE_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'TABLE_TYPE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'TABLE_LOAD_TYPE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (9, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_TABLE_COLUMNS (TABLE_ID = 10)
    (10, 'TABLE_COLUMN_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'TABLE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'COLUMN_NAME', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'DATA_TYPE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'FIELD_LENGTH', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'DESCRIPTION', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (10, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- CSD_DATA_MART (TABLE_ID = 11)
    (11, 'CSD_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'SOURCE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'SOURCE_SYSTEM_IDENTIFIER', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'AGENT_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'INTERACTION_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'SUPPORT_AREA_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'INTERACTION_STATUS', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'INTERACTION_TYPE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'CUSTOMER_TYPE_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'HANDLE_TIME', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'WORK_TIME', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'FIRST_CONTACT_RESOLUTION', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'QUERY_STATUS', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'SOLUTION_TYPE', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'CUSTOMER_RATING', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'SOURCE_HASH_KEY', 'VARCHAR', 255, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'DATA_LOAD_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'IS_VALID_DATA', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'ACTIVE_FLAG', 'TINYINT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'START_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (11, 'END_DATE', 'DATETIME', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),

    -- STREAMING_DATA_ARCHIVES (TABLE_ID = 12)
    (12, 'ARCHIVE_ID', 'INT', NULL, 'PRIMARY KEY OF THE TABLE', 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (12, 'STREAM_RECORD_ID', 'INT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59'),
    (12, 'STREAMING_DATA', 'TEXT', NULL, NULL, 1, CURRENT_TIMESTAMP, '2999-12-31 23:59:59');

COMMIT;